// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://uyleozhwzngnvyddfvni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5bGVvemh3em5nbnZ5ZGRmdm5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NTAwOTcsImV4cCI6MjA2ODMyNjA5N30.fLmjDxluOc6KSRas2i157D5KmaXcJTmkuzeyFZ2SM4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// The generated Database type is older than the deployed schema.
// Keep the client usable until types are regenerated from the production project.
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
