import { useCallback, useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Check, EyeOff, Flag, Loader2, MessageSquareHeart, Star, X } from 'lucide-react';
import { toast } from 'sonner';

type Post={id:string;categoria:string;sexo:string;faixa_etaria:string;conteudo:string;status:string;destaque:boolean;permitir_comentarios:boolean;conteudo_sensivel:boolean;criado_em:string};
type Report={id:string;postagem_id:string|null;comentario_id:string|null;motivo:string;detalhes:string|null;status:string;criado_em:string};
type Comment={id:string;postagem_id:string;conteudo:string;status:string;criado_em:string};
const labels:Record<string,string>={masculino:'Masculino',feminino:'Feminino',nao_binario:'Não binário'};

export default function AdminEntreNos(){
 const [posts,setPosts]=useState<Post[]>([]); const [reports,setReports]=useState<Report[]>([]); const [comments,setComments]=useState<Comment[]>([]); const [loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);const[p,r,c]=await Promise.all([supabase.from('entre_nos_postagens' as any).select('id,categoria,sexo,faixa_etaria,conteudo,status,destaque,permitir_comentarios,conteudo_sensivel,criado_em').order('criado_em',{ascending:false}),supabase.from('entre_nos_denuncias' as any).select('id,postagem_id,comentario_id,motivo,detalhes,status,criado_em').order('criado_em',{ascending:false}),supabase.from('entre_nos_comentarios' as any).select('id,postagem_id,conteudo,status,criado_em').order('criado_em',{ascending:false})]);if(p.error||r.error||c.error)toast.error('Falha ao carregar a moderação.');setPosts((p.data||[]) as unknown as Post[]);setReports((r.data||[]) as unknown as Report[]);setComments((c.data||[]) as unknown as Comment[]);setLoading(false)},[]);
 useEffect(()=>{load()},[load]);
 const moderate=async(id:string,changes:Record<string,unknown>)=>{const{data:{user}}=await supabase.auth.getUser();const{error}=await supabase.from('entre_nos_postagens' as any).update({...changes,moderado_por:user?.id,moderado_em:new Date().toISOString()}).eq('id',id);if(error)toast.error('Não foi possível salvar.');else await load()};
 const review=async(id:string,status:string)=>{const{data:{user}}=await supabase.auth.getUser();const{error}=await supabase.from('entre_nos_denuncias' as any).update({status,revisado_por:user?.id,revisado_em:new Date().toISOString()}).eq('id',id);if(error)toast.error('Não foi possível salvar.');else await load()};
 const moderateComment=async(id:string,status:string)=>{const{error}=await supabase.from('entre_nos_comentarios' as any).update({status}).eq('id',id);if(error)toast.error('Não foi possível moderar o comentário.');else await load()};
 const list=(status:string)=>posts.filter(p=>p.status===status);
 const PostList=({status}:{status:string})=><div className="space-y-3">{list(status).length===0?<p className="py-16 text-center text-muted-foreground">Nenhum item nesta fila.</p>:list(status).map(p=><Card key={p.id} className="rounded-2xl"><CardContent className="p-5"><div className="flex flex-wrap items-center gap-2"><Badge>{p.categoria.replace('_',' ')}</Badge><Badge variant="outline">{labels[p.sexo]} · {p.faixa_etaria}</Badge>{p.conteudo_sensivel&&<Badge variant="destructive">Sensível</Badge>}</div><p className="my-4 whitespace-pre-wrap text-sm leading-6">{p.conteudo}</p><div className="flex flex-wrap gap-2">{status==='pendente'&&<><Button size="sm" onClick={()=>moderate(p.id,{status:'aprovado'})}><Check className="mr-1 h-4 w-4"/>Aprovar</Button><Button size="sm" variant="destructive" onClick={()=>moderate(p.id,{status:'rejeitado'})}><X className="mr-1 h-4 w-4"/>Rejeitar</Button></>}{status==='aprovado'&&<><Button size="sm" variant="outline" onClick={()=>moderate(p.id,{destaque:!p.destaque})}><Star className="mr-1 h-4 w-4"/>{p.destaque?'Remover destaque':'Destacar'}</Button><Button size="sm" variant="outline" onClick={()=>moderate(p.id,{permitir_comentarios:!p.permitir_comentarios})}>{p.permitir_comentarios?'Fechar comentários':'Abrir comentários'}</Button><Button size="sm" variant="destructive" onClick={()=>moderate(p.id,{status:'oculto'})}><EyeOff className="mr-1 h-4 w-4"/>Ocultar</Button></>}{['rejeitado','oculto'].includes(status)&&<Button size="sm" onClick={()=>moderate(p.id,{status:'aprovado'})}>Restaurar e aprovar</Button>}</div></CardContent></Card>)}</div>;
 return <div className="space-y-6 p-4 md:p-6"><div><div className="flex items-center gap-3"><div className="rounded-2xl bg-primary/10 p-3"><MessageSquareHeart className="h-6 w-6 text-primary"/></div><div><h1 className="text-2xl font-black">Moderação · Entre Nós</h1><p className="text-sm text-muted-foreground">Proteja a comunidade sem expor a identidade dos participantes.</p></div></div></div>{loading?<div className="flex justify-center py-24"><Loader2 className="h-8 w-8 animate-spin"/></div>:<Tabs defaultValue="pending"><TabsList className="h-auto flex-wrap"><TabsTrigger value="pending">Pendentes ({list('pendente').length})</TabsTrigger><TabsTrigger value="published">Publicadas ({list('aprovado').length})</TabsTrigger><TabsTrigger value="comments">Comentários ({comments.filter(c=>c.status==='pendente').length})</TabsTrigger><TabsTrigger value="hidden">Ocultas/rejeitadas</TabsTrigger><TabsTrigger value="reports">Denúncias ({reports.filter(r=>r.status==='aberta').length})</TabsTrigger></TabsList><TabsContent value="pending"><PostList status="pendente"/></TabsContent><TabsContent value="published"><PostList status="aprovado"/></TabsContent><TabsContent value="comments"><div className="space-y-3">{comments.filter(c=>c.status==='pendente').map(c=><Card key={c.id} className="rounded-2xl"><CardContent className="p-5"><Badge variant="outline">Comentário pendente</Badge><p className="my-4 text-sm leading-6">{c.conteudo}</p><div className="flex gap-2"><Button size="sm" onClick={()=>moderateComment(c.id,'aprovado')}><Check className="mr-1 h-4 w-4"/>Aprovar</Button><Button size="sm" variant="destructive" onClick={()=>moderateComment(c.id,'rejeitado')}><X className="mr-1 h-4 w-4"/>Rejeitar</Button></div></CardContent></Card>)}</div></TabsContent><TabsContent value="hidden"><><PostList status="oculto"/><PostList status="rejeitado"/></></TabsContent><TabsContent value="reports"><div className="space-y-3">{reports.map(r=><Card key={r.id} className="rounded-2xl"><CardContent className="p-5"><div className="flex items-center gap-2"><Flag className="h-4 w-4 text-destructive"/><b>{r.motivo}</b><Badge variant={r.status==='aberta'?'destructive':'secondary'}>{r.status}</Badge></div><p className="my-3 text-sm text-muted-foreground">{r.detalhes||'Sem detalhes adicionais.'}</p>{r.status==='aberta'&&<div className="flex gap-2"><Button size="sm" onClick={()=>review(r.id,'resolvida')}>Marcar resolvida</Button><Button size="sm" variant="outline" onClick={()=>review(r.id,'descartada')}>Descartar</Button></div>}</CardContent></Card>)}</div></TabsContent></Tabs>}</div>;
}
